# Generated by Django 5.0 on 2024-01-21 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_teacher", models.TextField(verbose_name="About me")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LanguageInform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("English", "English"),
                            ("German", "German"),
                            ("French", "French"),
                            ("Ukrainian", "Ukrainian"),
                            ("Polish", "Polish"),
                        ],
                        max_length=15,
                        verbose_name="Teaching Language",
                    ),
                ),
                ("cost", models.FloatField(verbose_name="Cost")),
                (
                    "experience_language",
                    models.CharField(
                        choices=[
                            ("lessyear", "less than a year"),
                            ("oneyear", "one year"),
                            ("twoyears", "two years"),
                            ("threeyears", "two - three years"),
                            ("fiveyears", "three - five years"),
                            ("tenyears", "five - ten years"),
                            ("moretenyears", "more than ten years"),
                        ],
                        max_length=20,
                        verbose_name="Experience teaching language",
                    ),
                ),
                (
                    "status_language",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Status language",
                    ),
                ),
                (
                    "date_approval_language",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="teacher.teacher",
                    ),
                ),
            ],
        ),
    ]
