# Generated by Django 5.0 on 2024-01-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="languageinform",
            name="date_approval_language",
            field=models.DateTimeField(null=True),
        ),
    ]
