# Generated by Django 5.0 on 2024-01-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0002_alter_languageinform_date_approval_language"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="languageinform",
            unique_together={("teacher", "language")},
        ),
    ]
