# Generated by Django 5.0 on 2023-12-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="First Name")),
                (
                    "second_name",
                    models.CharField(max_length=30, verbose_name="Second Name"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "number_phone",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Number_phone"
                    ),
                ),
                ("date_registration", models.DateField(auto_now_add=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("m", "Male"), ("f", "Female")],
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                ("birthday", models.DateField(blank=True, verbose_name="Birthday")),
                (
                    "role",
                    models.CharField(
                        choices=[("student", "Student"), ("teacher", "Teacher")],
                        default="student",
                        max_length=7,
                        verbose_name="Role",
                    ),
                ),
                (
                    "status_email",
                    models.BooleanField(default=False, verbose_name="Status_email"),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
